"""add info for ot,labour

Revision ID: 0524448d5892
Revises: 51ce141071a4
Create Date: 2022-01-09 10:46:51.154245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0524448d5892'
down_revision = '51ce141071a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('labour', sa.Column('info', sa.Text(), nullable=True))
    op.add_column('operation', sa.Column('info', sa.Text(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('operation', 'info')
    op.drop_column('labour', 'info')
   
    # ### end Alembic commands ###
