"""patient table

Revision ID: 11fc3ca0cc86
Revises: 2b3284487355
Create Date: 2021-12-27 16:43:38.564059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11fc3ca0cc86'
down_revision = '2b3284487355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('patient', sa.Column('patient_id', sa.Integer(), autoincrement=True, nullable=False))
    op.execute('UPDATE patient SET patient_id=id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('patient', 'patient_id')

    
    # ### end Alembic commands ###
