"""treatment usage

Revision ID: 123a8fca2610
Revises: 3fdf9062540d
Create Date: 2021-12-28 21:45:08.918586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '123a8fca2610'
down_revision = '3fdf9062540d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(255), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('open', 'close', name='state'), nullable=True),
    sa.Column('created_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_usage_id'), 'treatment_usage', ['id'], unique=False)
    op.create_table('treatment_usage_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('treatment_usage_id', sa.BigInteger(), nullable=True),
    sa.Column('pharmacy_item_id', sa.BigInteger(), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(255), nullable=True),
    sa.Column('created_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_item_id'], ['pharmacy_item.id'], ),
    sa.ForeignKeyConstraint(['treatment_usage_id'], ['treatment_usage.id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_usage_item_id'), 'treatment_usage_item', ['id'], unique=False)
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_treatment_usage_item_id'), table_name='treatment_usage_item')
    op.drop_table('treatment_usage_item')
    op.drop_index(op.f('ix_treatment_usage_id'), table_name='treatment_usage')
    op.drop_table('treatment_usage')
    # ### end Alembic commands ###
