"""own inventory

Revision ID: 2b3284487355
Revises: c1179b6e0b05
Create Date: 2021-12-21 10:23:04.675468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b3284487355'
down_revision = 'c1179b6e0b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('inventorys', sa.Column('created_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventorys', sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventorys', sa.Column('created_user_id', sa.BigInteger(), nullable=False))
    op.add_column('inventorys', sa.Column('updated_user_id', sa.BigInteger(), nullable=False))
    op.execute("UPDATE inventorys SET updated_user_id = 1")
    op.execute("UPDATE inventorys SET created_user_id = 1")
    op.alter_column('inventorys', 'relation_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.create_index(op.f('ix_inventorys_id'), 'inventorys', ['id'], unique=False)
    op.create_foreign_key(None, 'inventorys', 'user', ['updated_user_id'], ['id'])
    op.create_foreign_key(None, 'inventorys', 'store_locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'inventorys', 'pharmacy_item', ['relation_id'], ['id'])
    op.create_foreign_key(None, 'inventorys', 'user', ['created_user_id'], ['id'])
    op.drop_column('inventorys', 'selling_price')
    op.drop_column('inventorys', 'resignment_flat')
    op.drop_column('inventorys', 'average_price')
   
    op.add_column('store_locations', sa.Column('created_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('store_locations', sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('store_locations', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('store_locations', sa.Column('created_user_id', sa.BigInteger(), nullable=False))
    op.add_column('store_locations', sa.Column('updated_user_id', sa.BigInteger(), nullable=False))
    op.execute("UPDATE store_locations SET updated_user_id = 1")
    op.execute("UPDATE store_locations SET created_user_id = 1")
    op.alter_column('store_locations', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.create_index(op.f('ix_store_locations_id'), 'store_locations', ['id'], unique=False)
    op.create_foreign_key(None, 'store_locations', 'user', ['updated_user_id'], ['id'])
    op.create_foreign_key(None, 'store_locations', 'user', ['created_user_id'], ['id'])
    op.drop_column('store_locations', 'detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_locations', sa.Column('detail', mysql.TEXT(charset='utf8', collation='utf8_unicode_ci'), nullable=True))
    op.drop_constraint(None, 'store_locations', type_='foreignkey')
    op.drop_constraint(None, 'store_locations', type_='foreignkey')
    op.drop_index(op.f('ix_store_locations_id'), table_name='store_locations')
    op.alter_column('store_locations', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.drop_column('store_locations', 'updated_user_id')
    op.drop_column('store_locations', 'created_user_id')
    op.drop_column('store_locations', 'description')
    op.drop_column('store_locations', 'updated_time')
    op.drop_column('store_locations', 'created_time')
    
    op.add_column('inventorys', sa.Column('average_price', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inventorys', sa.Column('resignment_flat', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=255), nullable=True))
    op.add_column('inventorys', sa.Column('selling_price', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventorys', type_='foreignkey')
    op.drop_constraint(None, 'inventorys', type_='foreignkey')
    op.drop_constraint(None, 'inventorys', type_='foreignkey')
    op.drop_constraint(None, 'inventorys', type_='foreignkey')
    op.drop_index(op.f('ix_inventorys_id'), table_name='inventorys')
    op.alter_column('inventorys', 'relation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('inventorys', 'updated_user_id')
    op.drop_column('inventorys', 'created_user_id')
    op.drop_column('inventorys', 'updated_time')
    op.drop_column('inventorys', 'created_time')
   
    # ### end Alembic commands ###
