"""add service_name column in psur

Revision ID: 3d2086a2d844
Revises: 212c9b6eced9
Create Date: 2021-12-29 22:41:04.301999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d2086a2d844'
down_revision = '212c9b6eced9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('patient_service_used_records', sa.Column('service_name', sa.String(255), nullable=True))
    op.execute('UPDATE patient_service_used_records SET service_name=(SELECT name FROM service_item WHERE patient_service_used_records.service_item_id=service_item.id);')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('patient_service_used_records', 'service_name')
   
    # ### end Alembic commands ###
