"""modfy usage item table

Revision ID: 3fdf9062540d
Revises: 2e0c3cd68bb1
Create Date: 2021-12-28 16:39:29.253896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fdf9062540d'
down_revision = '2e0c3cd68bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    op.add_column('operation_usage_item', sa.Column('unit', sa.String(255), nullable=True))
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.alter_column('operation_usage_item', 'inventory_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    
    # ### end Alembic commands ###
