"""add info column in treatment

Revision ID: 51ce141071a4
Revises: 3d2086a2d844
Create Date: 2022-01-02 22:00:48.396561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51ce141071a4'
down_revision = '3d2086a2d844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('treatment_usage', sa.Column('info', sa.Text(), nullable=True))
    op.create_index(op.f('ix_treatment_usage_reference_id'), 'treatment_usage', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_usage_reference_id'), table_name='treatment_usage')
    op.drop_column('treatment_usage', 'info')
    
    # ### end Alembic commands ###
