"""change user and role

Revision ID: 59d60ec8632c
Revises: 
Create Date: 2021-11-17 15:52:48.840164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59d60ec8632c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('users','user')
    op.drop_column('role', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('description', mysql.TEXT(), nullable=True))
    op.rename_table('user', 'users')
    
    # ### end Alembic commands ###
