"""modify status column in employee

Revision ID: 61afd79841f9
Revises: 6fda349c0b35
Create Date: 2021-12-09 10:14:01.361627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61afd79841f9'
down_revision = '6fda349c0b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee','status',
                    existing_type=sa.INTEGER(),
                    type_=sa.VARCHAR(length=255),
                    nullable=False
                    )
    op.execute('UPDATE employee SET status="resigned" WHERE status="0"')
    op.execute('UPDATE employee SET status="full_time" WHERE status="1"')
    op.execute('UPDATE employee SET status="part_time" WHERE status="2"')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.INTEGER(),
               nullable=False)
    
    # ### end Alembic commands ###
