"""modify status column to enum in employee

Revision ID: 64e730b15634
Revises: 61afd79841f9
Create Date: 2021-12-09 12:42:41.382787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from app.core.Entity.HR.employee import Status

# revision identifiers, used by Alembic.
revision = '64e730b15634'
down_revision = '61afd79841f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'status',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.ENUM(Status),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    op.alter_column('employee', 'status',
               existing_type=mysql.ENUM(Status),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
   
    # ### end Alembic commands ###
