"""modf user columns

Revision ID: 9eaa80b13c8b
Revises: 59d60ec8632c
Create Date: 2021-11-17 16:21:27.575497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9eaa80b13c8b'
down_revision = '59d60ec8632c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('user', sa.Column('role', sa.String(255), nullable=True))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=255),
               nullable=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_table_comment(
        'user',
        existing_comment='User Authentication',
        schema=None
    )
    op.drop_column('user', 'status')
    op.drop_column('user', 'created_user_id')
    op.drop_column('user', 'level')
    op.drop_column('user', 'updated_user_id')
    op.drop_column('user', 'updated_time')
    op.drop_column('user', 'created_time')
    op.drop_column('user', 'login_attempt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_attempt', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('created_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user', sa.Column('updated_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user', sa.Column('updated_user_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('level', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('created_user_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.create_table_comment(
        'user',
        'User Authentication',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=255),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    # ### end Alembic commands ###
