"""remove unit column in usage list

Revision ID: c1179b6e0b05
Revises: ff4f4724cf50
Create Date: 2021-12-20 20:59:43.826113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1179b6e0b05'
down_revision = 'ff4f4724cf50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_column('operation_usage_item', 'unit')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.add_column('operation_usage_item', sa.Column('unit', mysql.VARCHAR(length=255), nullable=True))
   
    # ### end Alembic commands ###
