"""change nullable in ot tables

Revision ID: d4d0fbce36a2
Revises: b4f95245c47b
Create Date: 2021-12-13 14:01:56.820327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4d0fbce36a2'
down_revision = 'b4f95245c47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('ot_inform', 'patient_id',
               existing_type=sa.BigInteger(),
               nullable=False)
    op.alter_column('operation', 'patient_id',
               existing_type=sa.BigInteger(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('ot_inform', 'patient_id',
               existing_type=sa.BigInteger(),
               nullable=True)
    op.alter_column('operation', 'patient_id',
               existing_type=sa.BigInteger(),
               nullable=True)
  
    # ### end Alembic commands ###
