"""supplier model added

Revision ID: d856920fa5ef
Revises: 9eaa80b13c8b
Create Date: 2021-11-21 11:17:00.944727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd856920fa5ef'
down_revision = '9eaa80b13c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.add_column('supplier', sa.Column('dealer', sa.String(length=32), nullable=True))
    op.add_column('supplier', sa.Column('company', sa.String(length=32), nullable=True))
    op.add_column('supplier', sa.Column('credit_term', sa.String(length=10), nullable=True))
    op.add_column('supplier', sa.Column('contact', sa.String(length=256), nullable=True))
    op.add_column('supplier', sa.Column('remark', sa.String(length=256), nullable=True))
    op.alter_column('supplier', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('supplier', 'updated_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_supplier_id'), 'supplier', ['id'], unique=False)
    op.create_foreign_key(None, 'supplier', 'user', ['updated_user_id'], ['id'])
    op.create_foreign_key(None, 'supplier', 'user', ['created_user_id'], ['id'])
    op.drop_column('supplier', 'name')
    op.drop_column('supplier', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('phone', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('supplier', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'supplier', type_='foreignkey')
    op.drop_constraint(None, 'supplier', type_='foreignkey')
    op.drop_index(op.f('ix_supplier_id'), table_name='supplier')
    op.alter_column('supplier', 'updated_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('supplier', 'created_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('supplier', 'remark')
    op.drop_column('supplier', 'contact')
    op.drop_column('supplier', 'credit_term')
    op.drop_column('supplier', 'company')
    op.drop_column('supplier', 'dealer')
    # op.drop_index(op.f('ix_role_id'), table_name='role')
   
    # ### end Alembic commands ###
