"""pharmacy item refined

Revision ID: f9b4648bf129
Revises: f7c37202eaf8
Create Date: 2021-11-25 16:38:43.845067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9b4648bf129'
down_revision = 'f7c37202eaf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.alter_column('pharmacy_item','name',nullable=False,existing_type=sa.String(255),new_column_name='brand_name')
    op.alter_column('pharmacy_item','abbr',nullable=True,existing_type=sa.String(244),new_column_name='packaging')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pharmacy_item','brand_name',existing_type=sa.String(255),nullable=False,new_column_name='name')
    op.alter_column('pharmacy_item','packaging',existing_type=sa.String(255),nullable=True,new_column_name='abbr')
   
    # ### end Alembic commands ###
